version: 2
updates:
  # Github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # init/autobuild/analyze must stay on the same version or CodeQL errors out
      codeql-action:
        patterns:
          - "github/codeql-action*"
  
  # Provider Go module
  - package-ecosystem: "gomod"
    directory: "./provider"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"

  # SDK Go module
  - package-ecosystem: "gomod"
    directory: "./sdk"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"

  # Examples Go module
  - package-ecosystem: "gomod"
    directory: "./examples"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"
