linters:
  enable:
    - errcheck
    - goconst
    - revive
    - gosec
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - unconvert
    - unused
  enable-all: false
run:
  skip-files:
    - schema.go
    - pulumiManifest.go
  timeout: 10m
