archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-ctfd
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/ctfer-io/pulumi-ctfd/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-ctfd/
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
sboms:
  - artifacts: source
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
