// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CTFerio.Ctfd
{
    /// <summary>
    /// CTFd is built around the Challenge resource, which contains all the attributes to define a part of the Capture The Flag event.
    /// 
    /// This provider builds a cleaner API on top of CTFd's one to improve its adoption and lifecycle management.
    /// </summary>
    [CtfdResourceType("ctfd:index/challenge:Challenge")]
    public partial class Challenge : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Category of the challenge that CTFd groups by on the web UI.
        /// </summary>
        [Output("category")]
        public Output<string> Category { get; private set; } = null!;

        /// <summary>
        /// Connection Information to connect to the challenge instance, useful for pwn, web and infrastructure pentests.
        /// </summary>
        [Output("connectionInfo")]
        public Output<string> ConnectionInfo { get; private set; } = null!;

        /// <summary>
        /// The decay defines from each number of solves does the decay function triggers until reaching minimum. This function is defined by CTFd and could be configured through `.function`.
        /// </summary>
        [Output("decay")]
        public Output<int?> Decay { get; private set; } = null!;

        /// <summary>
        /// Description of the challenge, consider using multiline descriptions for better style.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// List of files given to players to flag the challenge.
        /// </summary>
        [Output("files")]
        public Output<ImmutableArray<Outputs.ChallengeFile>> Files { get; private set; } = null!;

        /// <summary>
        /// List of challenge flags that solves it.
        /// </summary>
        [Output("flags")]
        public Output<ImmutableArray<Outputs.ChallengeFlag>> Flags { get; private set; } = null!;

        /// <summary>
        /// Decay function to define how the challenge value evolve through solves, either linear or logarithmic.
        /// </summary>
        [Output("function")]
        public Output<string> Function { get; private set; } = null!;

        /// <summary>
        /// List of hints about the challenge displayed to the end-user.
        /// </summary>
        [Output("hints")]
        public Output<ImmutableArray<Outputs.ChallengeHint>> Hints { get; private set; } = null!;

        /// <summary>
        /// Maximum amount of attempts before being unable to flag the challenge.
        /// </summary>
        [Output("maxAttempts")]
        public Output<int> MaxAttempts { get; private set; } = null!;

        /// <summary>
        /// The minimum points for a dynamic-score challenge to reach with the decay function. Once there, no solve could have more value.
        /// </summary>
        [Output("minimum")]
        public Output<int?> Minimum { get; private set; } = null!;

        /// <summary>
        /// Name of the file as displayed to end-users.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Suggestion for the end-user as next challenge to work on.
        /// </summary>
        [Output("next")]
        public Output<int?> Next { get; private set; } = null!;

        /// <summary>
        /// Other hints required to be consumed before getting this one. Useful for cost-increasing hint strategies with more and more help.
        /// </summary>
        [Output("requirements")]
        public Output<Outputs.ChallengeRequirements?> Requirements { get; private set; } = null!;

        /// <summary>
        /// State of the challenge, either hidden or visible.
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// List of challenge tags that will be displayed to the end-user. You could use them to give some quick insights of what a challenge involves.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// List of challenge topics that are displayed to the administrators for maintenance and planification.
        /// </summary>
        [Output("topics")]
        public Output<ImmutableArray<string>> Topics { get; private set; } = null!;

        /// <summary>
        /// The type of the flag, could be either static or regex
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// The value (points) of the challenge once solved. Internally, the provider will handle what target is legitimate depending on the `.type` value, i.e. either `value` for "standard" or `initial` for "dynamic".
        /// </summary>
        [Output("value")]
        public Output<int> Value { get; private set; } = null!;


        /// <summary>
        /// Create a Challenge resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Challenge(string name, ChallengeArgs args, CustomResourceOptions? options = null)
            : base("ctfd:index/challenge:Challenge", name, args ?? new ChallengeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Challenge(string name, Input<string> id, ChallengeState? state = null, CustomResourceOptions? options = null)
            : base("ctfd:index/challenge:Challenge", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ctfer-io/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Challenge resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Challenge Get(string name, Input<string> id, ChallengeState? state = null, CustomResourceOptions? options = null)
        {
            return new Challenge(name, id, state, options);
        }
    }

    public sealed class ChallengeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Category of the challenge that CTFd groups by on the web UI.
        /// </summary>
        [Input("category", required: true)]
        public Input<string> Category { get; set; } = null!;

        /// <summary>
        /// Connection Information to connect to the challenge instance, useful for pwn, web and infrastructure pentests.
        /// </summary>
        [Input("connectionInfo")]
        public Input<string>? ConnectionInfo { get; set; }

        /// <summary>
        /// The decay defines from each number of solves does the decay function triggers until reaching minimum. This function is defined by CTFd and could be configured through `.function`.
        /// </summary>
        [Input("decay")]
        public Input<int>? Decay { get; set; }

        /// <summary>
        /// Description of the challenge, consider using multiline descriptions for better style.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        [Input("files")]
        private InputList<Inputs.ChallengeFileArgs>? _files;

        /// <summary>
        /// List of files given to players to flag the challenge.
        /// </summary>
        public InputList<Inputs.ChallengeFileArgs> Files
        {
            get => _files ?? (_files = new InputList<Inputs.ChallengeFileArgs>());
            set => _files = value;
        }

        [Input("flags")]
        private InputList<Inputs.ChallengeFlagArgs>? _flags;

        /// <summary>
        /// List of challenge flags that solves it.
        /// </summary>
        public InputList<Inputs.ChallengeFlagArgs> Flags
        {
            get => _flags ?? (_flags = new InputList<Inputs.ChallengeFlagArgs>());
            set => _flags = value;
        }

        /// <summary>
        /// Decay function to define how the challenge value evolve through solves, either linear or logarithmic.
        /// </summary>
        [Input("function")]
        public Input<string>? Function { get; set; }

        [Input("hints")]
        private InputList<Inputs.ChallengeHintArgs>? _hints;

        /// <summary>
        /// List of hints about the challenge displayed to the end-user.
        /// </summary>
        public InputList<Inputs.ChallengeHintArgs> Hints
        {
            get => _hints ?? (_hints = new InputList<Inputs.ChallengeHintArgs>());
            set => _hints = value;
        }

        /// <summary>
        /// Maximum amount of attempts before being unable to flag the challenge.
        /// </summary>
        [Input("maxAttempts")]
        public Input<int>? MaxAttempts { get; set; }

        /// <summary>
        /// The minimum points for a dynamic-score challenge to reach with the decay function. Once there, no solve could have more value.
        /// </summary>
        [Input("minimum")]
        public Input<int>? Minimum { get; set; }

        /// <summary>
        /// Name of the file as displayed to end-users.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Suggestion for the end-user as next challenge to work on.
        /// </summary>
        [Input("next")]
        public Input<int>? Next { get; set; }

        /// <summary>
        /// Other hints required to be consumed before getting this one. Useful for cost-increasing hint strategies with more and more help.
        /// </summary>
        [Input("requirements")]
        public Input<Inputs.ChallengeRequirementsArgs>? Requirements { get; set; }

        /// <summary>
        /// State of the challenge, either hidden or visible.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// List of challenge tags that will be displayed to the end-user. You could use them to give some quick insights of what a challenge involves.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("topics")]
        private InputList<string>? _topics;

        /// <summary>
        /// List of challenge topics that are displayed to the administrators for maintenance and planification.
        /// </summary>
        public InputList<string> Topics
        {
            get => _topics ?? (_topics = new InputList<string>());
            set => _topics = value;
        }

        /// <summary>
        /// The type of the flag, could be either static or regex
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// The value (points) of the challenge once solved. Internally, the provider will handle what target is legitimate depending on the `.type` value, i.e. either `value` for "standard" or `initial` for "dynamic".
        /// </summary>
        [Input("value", required: true)]
        public Input<int> Value { get; set; } = null!;

        public ChallengeArgs()
        {
        }
        public static new ChallengeArgs Empty => new ChallengeArgs();
    }

    public sealed class ChallengeState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Category of the challenge that CTFd groups by on the web UI.
        /// </summary>
        [Input("category")]
        public Input<string>? Category { get; set; }

        /// <summary>
        /// Connection Information to connect to the challenge instance, useful for pwn, web and infrastructure pentests.
        /// </summary>
        [Input("connectionInfo")]
        public Input<string>? ConnectionInfo { get; set; }

        /// <summary>
        /// The decay defines from each number of solves does the decay function triggers until reaching minimum. This function is defined by CTFd and could be configured through `.function`.
        /// </summary>
        [Input("decay")]
        public Input<int>? Decay { get; set; }

        /// <summary>
        /// Description of the challenge, consider using multiline descriptions for better style.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("files")]
        private InputList<Inputs.ChallengeFileGetArgs>? _files;

        /// <summary>
        /// List of files given to players to flag the challenge.
        /// </summary>
        public InputList<Inputs.ChallengeFileGetArgs> Files
        {
            get => _files ?? (_files = new InputList<Inputs.ChallengeFileGetArgs>());
            set => _files = value;
        }

        [Input("flags")]
        private InputList<Inputs.ChallengeFlagGetArgs>? _flags;

        /// <summary>
        /// List of challenge flags that solves it.
        /// </summary>
        public InputList<Inputs.ChallengeFlagGetArgs> Flags
        {
            get => _flags ?? (_flags = new InputList<Inputs.ChallengeFlagGetArgs>());
            set => _flags = value;
        }

        /// <summary>
        /// Decay function to define how the challenge value evolve through solves, either linear or logarithmic.
        /// </summary>
        [Input("function")]
        public Input<string>? Function { get; set; }

        [Input("hints")]
        private InputList<Inputs.ChallengeHintGetArgs>? _hints;

        /// <summary>
        /// List of hints about the challenge displayed to the end-user.
        /// </summary>
        public InputList<Inputs.ChallengeHintGetArgs> Hints
        {
            get => _hints ?? (_hints = new InputList<Inputs.ChallengeHintGetArgs>());
            set => _hints = value;
        }

        /// <summary>
        /// Maximum amount of attempts before being unable to flag the challenge.
        /// </summary>
        [Input("maxAttempts")]
        public Input<int>? MaxAttempts { get; set; }

        /// <summary>
        /// The minimum points for a dynamic-score challenge to reach with the decay function. Once there, no solve could have more value.
        /// </summary>
        [Input("minimum")]
        public Input<int>? Minimum { get; set; }

        /// <summary>
        /// Name of the file as displayed to end-users.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Suggestion for the end-user as next challenge to work on.
        /// </summary>
        [Input("next")]
        public Input<int>? Next { get; set; }

        /// <summary>
        /// Other hints required to be consumed before getting this one. Useful for cost-increasing hint strategies with more and more help.
        /// </summary>
        [Input("requirements")]
        public Input<Inputs.ChallengeRequirementsGetArgs>? Requirements { get; set; }

        /// <summary>
        /// State of the challenge, either hidden or visible.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// List of challenge tags that will be displayed to the end-user. You could use them to give some quick insights of what a challenge involves.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("topics")]
        private InputList<string>? _topics;

        /// <summary>
        /// List of challenge topics that are displayed to the administrators for maintenance and planification.
        /// </summary>
        public InputList<string> Topics
        {
            get => _topics ?? (_topics = new InputList<string>());
            set => _topics = value;
        }

        /// <summary>
        /// The type of the flag, could be either static or regex
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// The value (points) of the challenge once solved. Internally, the provider will handle what target is legitimate depending on the `.type` value, i.e. either `value` for "standard" or `initial` for "dynamic".
        /// </summary>
        [Input("value")]
        public Input<int>? Value { get; set; }

        public ChallengeState()
        {
        }
        public static new ChallengeState Empty => new ChallengeState();
    }
}
