// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ctfd
{
    public static class GetChallenges
    {
        public static Task<GetChallengesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetChallengesResult>("ctfd:index/getChallenges:getChallenges", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetChallengesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetChallengesResult>("ctfd:index/getChallenges:getChallenges", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetChallengesResult
    {
        public readonly ImmutableArray<Outputs.GetChallengesChallengeResult> Challenges;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetChallengesResult(
            ImmutableArray<Outputs.GetChallengesChallengeResult> challenges,

            string id)
        {
            Challenges = challenges;
            Id = id;
        }
    }
}
