// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("ctfd");

/**
 * User API key. Could use `CTFD_API_KEY` environment variable instead. Despite being the most convenient way to
 * authenticate yourself, we do not recommend it as you will probably generate a long-live token without any rotation
 * policy.
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey");
    },
    enumerable: true,
});

/**
 * User session nonce, comes with session. Could use `CTFD_NONCE` environment variable instead.
 */
export declare const nonce: string | undefined;
Object.defineProperty(exports, "nonce", {
    get() {
        return __config.get("nonce");
    },
    enumerable: true,
});

/**
 * User session token, comes with nonce. Could use `CTFD_SESSION` environment variable instead.
 */
export declare const session: string | undefined;
Object.defineProperty(exports, "session", {
    get() {
        return __config.get("session");
    },
    enumerable: true,
});

/**
 * CTFd base URL (e.g. `https://my-ctf.lan`). Could use `CTFD_URL` environment variable instead.
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url");
    },
    enumerable: true,
});

