// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CTFerio.Ctfd.Outputs
{

    [OutputType]
    public sealed class GetBracketsUserResult
    {
        /// <summary>
        /// Description that explains the goal of this bracket.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Identifier of the bracket, used internally to handle the CTFd corresponding object.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name displayed to end-users (e.g. "Students", "Interns", "Engineers").
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Type of the bracket, either "users" or "teams".
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetBracketsUserResult(
            string description,

            string id,

            string name,

            string type)
        {
            Description = description;
            Id = id;
            Name = name;
            Type = type;
        }
    }
}
