# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apiKey: Optional[str]
"""
User API key. Could use `CTFD_API_KEY` environment variable instead. Despite being the most convenient way to
authenticate yourself, we do not recommend it as you will probably generate a long-live token without any rotation
policy.
"""

nonce: Optional[str]
"""
User session nonce, comes with session. Could use `CTFD_NONCE` environment variable instead.
"""

session: Optional[str]
"""
User session token, comes with nonce. Could use `CTFD_SESSION` environment variable instead.
"""

url: Optional[str]
"""
CTFd base URL (e.g. `https://my-ctf.lan`). Could use `CTFD_URL` environment variable instead.
"""

