name: lint

on:
  workflow_call:
    inputs: {}
  push: {}
  pull_request:
    branches:
    - main
    - v*
    - feature*

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: 'docs/*.md'

      - name: Install go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'provider/go.mod'

      - name: disarm go:embed directives to enable lint
        continue-on-error: true # this fails if there are no go:embed directives
        run: |
          git grep -l 'go:embed' -- provider | xargs sed -i 's/go:embed/ goembed/g'

      - run: cd provider && go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          working-directory: provider
