// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBrackets(opts?: pulumi.InvokeOptions): Promise<GetBracketsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ctfd:index/getBrackets:getBrackets", {
    }, opts);
}

/**
 * A collection of values returned by getBrackets.
 */
export interface GetBracketsResult {
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly users: outputs.GetBracketsUser[];
}
export function getBracketsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBracketsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ctfd:index/getBrackets:getBrackets", {
    }, opts);
}
