// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ChallengeArgs, ChallengeState } from "./challenge";
export type Challenge = import("./challenge").Challenge;
export const Challenge: typeof import("./challenge").Challenge = null as any;
utilities.lazyLoad(exports, ["Challenge"], () => require("./challenge"));

export { GetChallengesResult } from "./getChallenges";
export const getChallenges: typeof import("./getChallenges").getChallenges = null as any;
export const getChallengesOutput: typeof import("./getChallenges").getChallengesOutput = null as any;
utilities.lazyLoad(exports, ["getChallenges","getChallengesOutput"], () => require("./getChallenges"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "ctfd:index/challenge:Challenge":
                return new Challenge(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("ctfd", "index/challenge", _module)
pulumi.runtime.registerResourcePackage("ctfd", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:ctfd") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
